version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/node:16'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'npm ci'
      - run:
          name: Run Test
          command:  npm run test:c
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud